### ISSUE TITLE
'all' returns empty array

### ISSUE THREAD

**Issue by mkazlauskas** [pierrecle/node-red-contrib-mi-devices#20]
I'm not sure if I'm just using it wrong or it's actually a bug, but I'm getting an empty array of devices, even though I have them successfully connected via the app. I've also successfully used this gateway using Home Assistant.

![flow](https://i.imgur.com/OkVFrNm.png)
![all](https://i.imgur.com/lZynY9h.png)
![output](https://i.imgur.com/3OdkDOd.png)

**Comment by bemble** [comment]
You're right, I broke the device list in a previous update.
I fixed it, I'll release soon.

**Comment by mkazlauskas** [comment]
Would you mind tagging a release for just this fix while the other 1.1.2 thing is in development?

**Comment by bemble** [comment]
I'll release v2.0.0 next week which brings a complete rewrite, node renaming & many fixes/enhancements. Because of the breaking change between 1.X and 2.X, no need, for my point of view, to release a quick fix like this, because the xiaomi-devices nodes won't exist in 2.X under the same name (sorry for that, but it was needed to change node name form the initial fork).
